// 儿童谜语库（精选100个谜语）

const riddleLibrary = [
    { id: 1, question: "什么东西越洗越脏？", answer: "水" },
    { id: 2, question: "什么球不能踢？", answer: "眼球" },
    { id: 3, question: "什么蛋不能吃？", answer: "脸蛋" },
    { id: 4, question: "什么东西越剪越大？", answer: "洞" },
    { id: 5, question: "什么东西有头无脚？", answer: "针" },
    { id: 6, question: "什么车不能坐？", answer: "风车" },
    { id: 7, question: "什么书不能读？", answer: "说明书" },
    { id: 8, question: "什么花不能摘？", answer: "火花" },
    { id: 9, question: "什么水不能喝？", answer: "薪水" },
    { id: 10, question: "什么字人人都会念错？", answer: "错字" },
    { id: 11, question: "什么东西越热越爱出来？", answer: "汗" },
    { id: 12, question: "什么东西有面没有口，有脚没有手？", answer: "桌子" },
    { id: 13, question: "什么东西有头没有身？", answer: "钉子" },
    { id: 14, question: "什么东西越洗越脏？", answer: "水" },
    { id: 15, question: "什么东西晚上才生出尾巴？", answer: "流星" },
    { id: 16, question: "什么门永远关不上？", answer: "球门" },
    { id: 17, question: "什么路最窄？", answer: "冤家路" },
    { id: 18, question: "什么蛋中看不中吃？", answer: "脸蛋" },
    { id: 19, question: "什么人整天坐在火上？", answer: "消防员" },
    { id: 20, question: "什么鱼不能吃？", answer: "木鱼" },
    { id: 21, question: "什么河没有水？", answer: "银河" },
    { id: 22, question: "什么马不会跑？", answer: "木马" },
    { id: 23, question: "什么鸡没有翅膀？", answer: "田鸡" },
    { id: 24, question: "什么狗不会叫？", answer: "热狗" },
    { id: 25, question: "什么猫不吃鱼？", answer: "熊猫" },
    { id: 26, question: "什么虎不吃人？", answer: "壁虎" },
    { id: 27, question: "什么羊不吃草？", answer: "替罪羊" },
    { id: 28, question: "什么牛不吃草？", answer: "蜗牛" },
    { id: 29, question: "什么鼠不怕猫？", answer: "鼠标" },
    { id: 30, question: "什么鸟不会飞？", answer: "鸵鸟" },
    { id: 31, question: "什么东西有五个头？", answer: "手（五个手指头）" },
    { id: 32, question: "什么东西越分越少？", answer: "蛋糕" },
    { id: 33, question: "什么东西越晒越湿？", answer: "冰" },
    { id: 34, question: "什么东西越洗越脏？", answer: "抹布" },
    { id: 35, question: "什么东西越擦越小？", answer: "橡皮" },
    { id: 36, question: "什么东西越用越亮？", answer: "眼睛" },
    { id: 37, question: "什么东西越磨越小？", answer: "铅笔" },
    { id: 38, question: "什么东西越转越稳？", answer: "陀螺" },
    { id: 39, question: "什么东西越冷越爱出？", answer: "鼻涕" },
    { id: 40, question: "什么东西越老越值钱？", answer: "古董" },
    { id: 41, question: "有头没有尾，有角没有嘴。摇动身体发出声，猜猜我是谁？", answer: "铃铛" },
    { id: 42, question: "有面没有口，有脚没有手。虽有几只脚，自己不会走。", answer: "桌子" },
    { id: 43, question: "有头没有脑，有脚不会跑。每天站在门口，欢迎客人到。", answer: "鞋柜" },
    { id: 44, question: "有眼看不见，有耳听不见。有口不说话，有脚不会走。", answer: "娃娃" },
    { id: 45, question: "有嘴不说话，有手不会拿。有脚不会走，有头没有发。", answer: "衣服" },
    { id: 46, question: "一个小姑娘，生在水中央。身穿粉红衫，坐在绿船上。", answer: "荷花" },
    { id: 47, question: "一个小胖子，最爱晒太阳。穿着红衣裳，切开蜜糖香。", answer: "西瓜" },
    { id: 48, question: "一个小杯子，装满红珠子。咬开看一看，里面是白籽。", answer: "石榴" },
    { id: 49, question: "一个小灯笼，挂在树梢中。绿色当外套，红色当灯笼。", answer: "柿子" },
    { id: 50, question: "一个小刺猬，穿着黄外衣。剥开看一看，里面是白米。", answer: "板栗" },
    { id: 51, question: "身上穿绿袍，肚里有红宝。红宝里面藏白肉，猜猜是什么好？", answer: "西瓜" },
    { id: 52, question: "兄弟七八个，围着柱子坐。一旦要分开，衣服全撕破。", answer: "大蒜" },
    { id: 53, question: "头戴绿帽子，身穿白袍子。脚穿红鞋子，猜猜是什么？", answer: "萝卜" },
    { id: 54, question: "身穿黄衣裳，弯弯像月亮。兄弟排一起，个个甜蜜蜜。", answer: "香蕉" },
    { id: 55, question: "红脸蛋，绿衣裳。咬一口，甜又香。", answer: "苹果" },
    { id: 56, question: "白天出现，晚上不见。有它不用灯，没它看不见。", answer: "太阳" },
    { id: 57, question: "有时挂山腰，有时挂树梢。有时像圆盘，有时像镰刀。", answer: "月亮" },
    { id: 58, question: "千条线，万条线。落到水里看不见。", answer: "雨" },
    { id: 59, question: "像糖不是糖，像盐不是盐。人见人讨厌，庄稼见了甜。", answer: "化肥" },
    { id: 60, question: "像花不是花，冬天开白花。太阳一出来，变成水娃娃。", answer: "雪花" },
    { id: 61, question: "天上一片片，地上看不见。风来它就跑，雨来它就散。", answer: "云" },
    { id: 62, question: "生来本无形，动来就有声。夏天它常来，冬天不见影。", answer: "风" },
    { id: 63, question: "有时弯弯，有时圆圆。晚上出来，白天不见。", answer: "月亮" },
    { id: 64, question: "青石板，石板青。青石板上钉银钉。", answer: "星星" },
    { id: 65, question: "黑黑一座房，里面住满人。人人穿白衣，排排站整齐。", answer: "火柴盒" },
    { id: 66, question: "小小一间房，有门没有窗。只要你进去，立刻就发光。", answer: "冰箱" },
    { id: 67, question: "小小铁马儿，不吃草和米。骑上跑得快，人人夸它好。", answer: "自行车" },
    { id: 68, question: "小小铁房子，里面装数字。一按它就响，猜猜是什么？", answer: "计算器" },
    { id: 69, question: "小小圆盒子，装着银色线。线头连着耳，听着就入迷。", answer: "耳机" },
    { id: 70, question: "一张大嘴巴，什么都吃下。吃了不消化，吐出来才罢。", answer: "碎纸机" },
    { id: 71, question: "一张大网天上挂，里面装着雪花。轻轻一按就下雨，花儿见了笑哈哈。", answer: "淋浴头" },
    { id: 72, question: "一个小方块，藏着全世界。轻轻点一点，知识全出来。", answer: "手机" },
    { id: 73, question: "一个小娃娃，嘴大肚子大。吃进脏东西，吐出干净渣。", answer: "吸尘器" },
    { id: 74, question: "一个小房子，里面住数字。手指轻轻按，答案就出来。", answer: "计算器" },
    { id: 75, question: "一个小盒子，能说又会唱。里面住着人，天天不一样。", answer: "收音机" },
    { id: 76, question: "一个大肚皮，生来爱喝水。喝水就跳舞，跳完就休息。", answer: "洗衣机" },
    { id: 77, question: "一个大嘴巴，最爱吃衣服。吃完转圈圈，吐出来更干净。", answer: "洗衣机" },
    { id: 78, question: "一个大盒子，里面冰冰凉。放进去的热，拿出来是凉。", answer: "冰箱" },
    { id: 79, question: "一个长方盒，里面住火娃。插上电源线，火娃就发热。", answer: "电饭煲" },
    { id: 80, question: "一个圆脑袋，戴着小帽子。一按就冒烟，饭菜就熟了。", answer: "电饭煲" },
    { id: 81, question: "一个圆身子，头上长叶子。风吹它就转，发电靠它力。", answer: "风力发电机" },
    { id: 82, question: "一根小棍子，头上戴帽子。帽子能发光，照亮全世界。", answer: "手电筒" },
    { id: 83, question: "一根长管子，一头大来一头小。大的一头吸水，小的一头冒水。", answer: "漏斗" },
    { id: 84, question: "两只小耳朵，一条长尾巴。白天睡大觉，晚上捉老鼠。", answer: "猫" },
    { id: 85, question: "耳朵长，尾巴短。红眼睛，白毛衫。三瓣嘴，胆子小。蹦蹦跳跳爱萝卜。", answer: "兔子" },
    { id: 86, question: "黑毛亮，白毛亮。爱吃竹子，身体胖。", answer: "熊猫" },
    { id: 87, question: "身穿花衣裳，唱歌呱呱呱。捉虫是能手，庄稼喜欢它。", answer: "青蛙" },
    { id: 88, question: "身穿绿衣裳，头顶红帽子。捉虫本领高，最爱吃虫子。", answer: "啄木鸟" },
    { id: 89, question: "身穿黑礼服，尾巴像剪刀。春天飞回来，秋天飞南方。", answer: "燕子" },
    { id: 90, question: "身穿白大褂，尾巴像扇子。脖子长又长，爱吃树叶子。", answer: "长颈鹿" },
    { id: 91, question: "头上长树杈，身上开梅花。冬天换新衣，春天又换下。", answer: "梅花鹿" },
    { id: 92, question: "身上有斑纹，跑得快又快。爱吃肉和草，草原是它家。", answer: "斑马" },
    { id: 93, question: "鼻子长又长，耳朵像扇子。身体像堵墙，腿上像柱子。", answer: "大象" },
    { id: 94, question: "嘴巴大又大，眼睛圆又圆。水里游得快，岸上懒洋洋。", answer: "河马" },
    { id: 95, question: "背上背房子，头上长触角。走路慢吞吞，下雨就躲藏。", answer: "蜗牛" },
    { id: 96, question: "没有脚，没有手。游在水里像条蛇。", answer: "黄鳝" },
    { id: 97, question: "没有脚，没有手。身上长满鳞，水里游啊游。", answer: "鱼" },
    { id: 98, question: "没有手，没有脚。在土里钻来钻去，帮助庄稼松土壤。", answer: "蚯蚓" },
    { id: 99, question: "小小一姑娘，坐在水中央。身穿粉红衣，撑船不用桨。", answer: "荷花" },
    { id: 100, question: "一个小姑娘，生在水中央。身穿白衣裳，坐在绿船上。", answer: "荷花" }
];

// 随机获取一个谜语
function getRandomRiddle() {
    if (riddleLibrary.length === 0) return null;
    const randomIndex = Math.floor(Math.random() * riddleLibrary.length);
    return riddleLibrary[randomIndex];
}

// 根据ID获取谜语
function getRiddleById(id) {
    return riddleLibrary.find(r => r.id === id);
}